### ISSUE TITLE
Lets consider using .github instead for this content

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/org#1]
.github directory is already a centralish place to have these kinds of org wide metadata I think and maybe this content can live there instead.

Counter point: it seems mostly used for tools and not so much for humans.

**Comment by gianarb** [comment]
Ideally, I would like to see this repo used as infrastructure as code for GitHub related work:

1. Add a new contributor to a project
2. Create a new team
3. Ask for a new repository
4. Create ad assign labels to projects
5. Who knows what

We can do it in `.github` but `.github` is a template as well and if I understood how a template works files and directories get moved to all the repositories created from that template. And this is not what I would like

**Comment by mmlb** [comment]
I mentioned .github because probot apps should be able to look for config files for the apps there by default so some of those things might come for free with probot apps or ones we could write. This could apply for points 1-3 I think.

4. Should already be the case from the .github's own labels. But its only for new repos.

It doesn't look like .github is a template repo, its not checked in the settings.

**Comment by gianarb** [comment]
I am on it! This repo will be archived
