### ISSUE TITLE
governance role invitations

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/org#10]
# Tinkerbell Role Bootstrapping

The following is the proposal for role bootstrapping. See the governance ([here](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)) for definitions, details, responsibilities, etc on each role.

## Response Requested

<img src="https://user-images.githubusercontent.com/12081036/161319277-ae464dff-4fa4-434f-859f-e80bf5870a38.png" width="25" height="25" /> **To accept or decline a role, please comment in this issue with the repository and role name, and whether you accept this role or not.** <img src="https://user-images.githubusercontent.com/12081036/161319277-ae464dff-4fa4-434f-859f-e80bf5870a38.png" width="25" height="25" />

| Repository | Maintainers | Approvers | Reviewers |
| --------- | ---------- | ---------- | ---------- |
| [tink](https://github.com/tinkerbell/tink)      | @mmlb,@micahhausler   | @jacobweinstock, @tstromberg, @displague, @nshalman | @tobert, @stephen-fox, @chrisdoherty4, @detiber |
| [boots](https://github.com/tinkerbell/boots)     | @mmlb,@jacobweinstock   | @tobert, @nshalman, @tstromberg, @rgl | @mikemrm, @ScottGarman, @displague, @dlaube |
| [hegel](https://github.com/tinkerbell/hegel)     | @nshalman, @mmlb, @chrisdoherty4  | @tstromberg, @displague   | @jacobweinstock, @splaspood |
| [pbnj](https://github.com/tinkerbell/pbnj)      | @jacobweinstock   | @nshalman, @joelrebel | @tstromberg, @mmlb, @abhay-krishna, @Raj-Dharwadkar, @nhorman |
| [sandbox](https://github.com/tinkerbell/sandbox)   | @jacobweinstock, @mmlb    | @displague, @detiber  | @ProvenGuilty, @nshalman  |
| [ipxedust](https://github.com/tinkerbell/ipxedust)  | @jacobweinstock   | @mmlb | @stephen-fox, @nshalman, @Raj-Dharwadkar, @rgl |
| [dhcp](https://github.com/tinkerbell/dhcp)      | @jacobweinstock   | @nshalman | @displague, @tobert |
| [lint-install](https://github.com/tinkerbell/lint-install)  | @tstromberg   | @mmlb, @stephen-fox   | @jacobweinstock, @displague, @Raj-Dharwadkar |
| [hook](https://github.com/tinkerbell/hook)      | @thebsdbox    | @tstromberg, @mmlb    | @jmpolom, @ScottGarman, @jacobweinstock, @Raj-Dharwadkar |
| [hub](https://github.com/tinkerbell/hub)       | @thebsdbox, @nshalman | @mmlb, @displague | @alienninja, @jacobweinstock, @stephen-fox |
| [cluster-api-provider-tinkerbell](https://github.com/tinkerbell/cluster-api-provider-tinkerbell) | @detiber, @displague, @micahhausler  | @tstromberg | @mmlb |
| [crocodile](https://github.com/tinkerbell/crocodile) | @thebsdbox, @mmlb | @tstromberg, @dlaube | @jeremytanner, @rgl |
| [terraform-provider-tinkerbell](https://github.com/tinkerbell/terraform-provider-tinkerbell) | @jeremytanner | @mmlb, @displague | @jacobweinstock |
| [tinkerbell-docs](https://github.com/tinkerbell/tinkerbell-docs)   | @DailyAlice, @displague   | @mmlb, @tstromberg    | @rgl, @cprivitere, @felixwidjaja, @jacobweinstock |
| [k8s-sandbox](https://github.com/tinkerbell/k8s-sandbox)   | @detiber  | @tstromberg   | @sheepcat, @mmlb |
| [infrastructure](https://github.com/tinkerbell/infrastructure)   | @mmlb | @tstromberg   | @rawkode |

## Implementation Details

Each person was selected for a role based on their contributions and history in the repo. Load in other areas of the Tinkerbell project was also taken into account. Contributions were pulled from the CNCF's [devstats](https://tinkerbell.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m) tool. The script found [here](https://gist.github.com/jacobweinstock/f63f2dc9f32fe00a0aab08bcd7798bf5) was used to get the data.

## FAQ

What if I don't want to have a role?
> No worries. There is no obligation. This is an invitation based on your recent history of activity and contribution to the Tinkerbell community and project.

What if I wanted to have a specific role but I'm not?
> Your desire is awesome! This is just a one-time bootstrap process. Please follow the existing [governance](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md) on how to become the role for your desired repository.

What if I'm not even a member of the Tinkerbell org?
> First off, thank you for contributing! You rock. As part of this bootstrapping process, and if you accept, you will be added to the Tinkerbell org and the proposed role. 

What should be done if a role or roles in a repo are "short-staffed"?
> If a repo is "short-staffed" for roles, the repo's maintainer(s) can propose others to be an Approver or Reviewer. If there are no objections from any other maintainer(s) across the Tinkerbell org then the individual should be added to the role. This will be a one-time bootstrapping activity. After the bootstrapping process is complete individuals should follow the existing [governance](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md).

## Response Tracking
List of all people invited to a role. A checked box indicates the individual has responded to the invitation.
- [x] @DailyAlice
- [ ] @ProvenGuilty
- [x] @Raj-Dharwadkar
- [x] @ScottGarman
- [x] @abhay-krishna
- [x] @alienninja
- [x] @chrisdoherty4
- [x] @cprivitere
- [x] @detiber
- [x] @displague
- [x] @dlaube
- [x] @felixwidjaja
- [x] @jacobweinstock
- [x] @jeremytanner
- [x] @jmpolom
- [x] @joelrebel
- [x] @johalun
- [x] @micahhausler
- [x] @mikemrm
- [x] @mmlb
- [ ] @nhorman
- [x] @nshalman
- [x] @rawkode
- [x] @rgl
- [ ] @sheepcat
- [x] @splaspood
- [x] @stephen-fox
- [x] @thebsdbox
- [x] @tobert
- [x] @tstromberg

**Comment by jacobweinstock** [comment]
Hello, I accept all role invitations. Thank you.

**Comment by displague** [comment]
Thanks for preparing this @jacobweinstock! I accept all role invitations. Thanks.

**Comment by rawkode** [comment]
Happy to review Infrastructure 💯

**Comment by micahhausler** [comment]
I the invitation to be a maintainer of Tink! If we're short on folks for any role in cluster-api, I'm happy to help there too

**Comment by cprivite** [comment]
I accept the reviewer nomination for tinkerbell-docs.

**Comment by Raj-Dharwadkar** [comment]
I accept reviewer invitations for pbnj, ipxedust, hook and lint-install. Thank you!

**Comment by jmpolom** [comment]
I accept being a reviewer for hook.

**Comment by jacobweinstock** [comment]
> I the invitation to be a maintainer of Tink! If we're short on folks for any role in cluster-api, I'm happy to help there too

awesome, thank you.

@displague, you are a maintainer for CAPT, up to you if you would like to nominate. No objections from me. See the FAQ above on "_What should be done if a role or roles in a repo are "short-staffed"?_"

**Comment by displague** [comment]
Definitely appreciated and accepted, @micahhausler

**Comment by chrisdoherty4** [comment]
I accept being a reviewer for Tink

**Comment by jacobweinstock** [comment]
> Definitely appreciated and accepted, @micahhausler

Hey. @displague. To which role in CAPT would you like me to add Micah?

**Comment by DailyAlice** [comment]
I can definitely help out with docs! I accept being a maintainer for `tinkerbell-docs`.

**Comment by mmlb** [comment]
I accept my roles.

**Comment by felixwidjaja** [comment]
I accept being `reviewer` role at `tinkerbell-docs`.  
Thanks 🙏

**Comment by nshalman** [comment]
I accept the following role invitations:

| Repo | Role |
-------|------
| tink | approver |
| boots | approver |
| hegel | maintainer |
| pbnj | approver |
| sandbox | reviewer |
| ipxedust | reviewer |
| dhcp | approver |
| hub | maintainer |

**Comment by jeremytanner** [comment]
I accept review `crocodile` / maintain  `terraform-provider-tinkerbell`

**Comment by detiber** [comment]
I accept review `tink`, approver `sandbox`, maintainer `cluster-api-provider-tinkerbell`.

For `k8s-sandbox`, I'd like to suggest that we archive it in favor of tracking work to update `sandbox` to support kubernetes.

**Comment by joelrebel** [comment]
I accept the approver role for `pbnj`.

**Comment by displague** [comment]
@jacobweinstock 

@micahhausler's interest in maintainership of capt matches the commitment level on tink - it's great to see! (sgtm)

**Comment by thebsdbox** [comment]
I **formally** accepted my roles !

**Comment by jacobweinstock** [comment]
> I'd like to tender myself for consideration as a maintainer of Hegel. I recognize its slightly premature but figured I would throw it out there given the refactoring I'm doing (lots more to come).
> 
> @nshalman @mmlb @jacobweinstock @displague

I'm all for it! The process during this one time bootstrap event calls for the maintainers (@nshalman and @mmlb) to make this type of call.

**Comment by ScottGarman** [comment]
I accept my role invitations for boots and hook.

**Comment by tobert** [comment]
I accept for boots & dhcp.

**Comment by splaspood** [comment]
I accept the reviewer nomination for hegel.  :)

**Comment by mikemrm** [comment]
I accept my role invitations

**Comment by dlaube** [comment]
I accept my role invitations.

**Comment by stephen-fox** [comment]
Hi Jacob - I accept my reviewer role for `tink`, `ipxe-dust`, and `hub`. I also accept my approver role for `lint-install`.

**Comment by rgl** [comment]
I accept my role invitations.

| role | repositories |
|-------|-----------------|
| approver | [boots](https://github.com/tinkerbell/boots) |
| reviewer | [ipxedust](https://github.com/tinkerbell/ipxedust), [crocodile](https://github.com/tinkerbell/crocodile), [tinkerbell-docs](https://github.com/tinkerbell/tinkerbell-docs) |

**Comment by alienninja** [comment]
I accept my role nomination for hub reviewer.  Thanks!

**Comment by abhay-krishna** [comment]
I accept my `Reviewer` role nomination for `pbnj`. Thank you for the consideration!

**Comment by tstromberg** [comment]
I accept my nominations. Thank you for organizing this!

**Comment by johalun** [comment]
I'm sorry but I have to decline due to having other commitments.

**Comment by mmlb** [comment]
> I'd like to tender myself for consideration as a maintainer of Hegel. I recognize its slightly premature but figured I would throw it out there given the refactoring I'm doing (lots more to come).
> 
> @nshalman @mmlb @jacobweinstock @displague

Works for me. Prematureness aside, Hegel can definitely benefit from a dedicated maintainer!

**Comment by jacobweinstock** [comment]
> > I'd like to tender myself for consideration as a maintainer of Hegel. I recognize its slightly premature but figured I would throw it out there given the refactoring I'm doing (lots more to come).
> > @nshalman @mmlb @jacobweinstock @displague
> 
> Works for me. Prematureness aside, Hegel can definitely benefit from a dedicated maintainer!

I have added @chrisdoherty4 to the table above as a maintainer for Hegel, thanks!

**Comment by chrisdoherty4** [comment]
@jacobweinstock What's left to do so we can close?

**Comment by displague** [comment]
The previously maintained (now outdated) GitHub Teams for `admins`, `writers`, triage, and others have been removed.

The probot monitored .github/settings.yml lists are now authoritative.

**Comment by displague** [comment]
We'll want to add https://github.com/tinkerbell/tinkerbell.org to the list of projects under governance.
