### ISSUE TITLE
Request for new GH repo, "rufio"

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/org#11]
As we at AWS (mainly @pokearu) have looked into refactoring PBnJ to run as a kubernetes controller (tinkerbell/pbnj#121), the paradigm is very different from the current "PBnJ as a server" architecture. I have [a branch of pbnj](https://github.com/micahhausler/pbnj/commit/31aa505ca2fa3194db2384e6f5cdc28a8b9d7e99) adding some kubebuilder-generated scaffolding, but it became obvious to me that almost no code will be re-used, and there is a lot of modification to get the kubebuilder generated pieces to play nice. PBnJ has make targets that overlap with the kube-builder generated makefile, and existing make targets like `make image` would need to be refactored for multiple images.

Given the difference in architecture and maintenance, I propose a new GitHub repo. This is similar to how Hook replaced OSIE.

I propose the name "Rufio" after the character from the 1991 movie [_Hook_](https://www.imdb.com/title/tt0102057/).

**Comment by thebsdbox** [comment]
![15W8pX5](https://user-images.githubusercontent.com/1658918/163013623-82bb8558-adba-4de6-b0ca-1e0b8038c92e.gif)

Loving Rufio

**Comment by micahhausler** [comment]
> How would we describe Rufio, and most importantly what is the backronym?

The goals are largely the same, but the implementation and architecture is the difference.

Goals:

* Declaratively enforce and ensure BMC state such as:
  * Power state
  * Persistent boot order
  * NTP/LDAP/TLS Cert configuration (probably future scope)
 * Declaratively enact actions such as:
   *  Power reset
   * Configure ephemeral boot order
* Report state such as:
  * Firmware version 
  * Other Redfish/Swordfish machine metadata

Implementation
* Kubernetes-based controller instead of gRPC server
* AuthN/Z is enforced with Kubernetes Authentication/RBAC instead of a gRPC API
* BMC authentication is managed with Kubernetes Secrets instead of passed through per-request by clients 

> How would we describe Rufio, and most importantly what is the backronym?

Rufio is a declarative state manager for BMCs.

[Rufio](https://www.imdb.com/title/tt0102057/characters/nm0002364?ref_=tt_cl_c_14) is the leader of the Lost Boys in the 1991 movie _[Hook](https://www.imdb.com/title/tt0102057/)_.

**Comment by chrisdoherty4** [comment]
> [Rufio](https://www.imdb.com/title/tt0102057/characters/nm0002364?ref_=tt_cl_c_14) is the leader of the Lost Boys in the 1991 movie [Hook](https://www.imdb.com/title/tt0102057/).

How on earth did you come up with that one, love it!

**Comment by rothgar** [comment]
If we're going to re-brand PBnJ (or fork it) I would like to throw out the name "dust"

Pixie dust is the magic of flying in the clouds (as long as you have happy thoughts).

If you want a backronym

D ust
U pdates
S tate for
T inkerbell

I :heart: Rufio. It has been 31 years and it's still too soon :cry: 

I'm fine with either (they're both better than PBnJ) but wanted to suggest my idea from [last year](https://twitter.com/rothgar/status/1379814865947095041).

**Comment by thebsdbox** [comment]
So the name tinkerbell I believe was chosen due to the fact that the whole platform is powered by PXE dust. 😂

**Comment by rothgar** [comment]
I have no idea how I didn't even know that was a repo. I retract my suggestion. That would be very confusing.

**Comment by chrisdoherty4** [comment]
What about 'brig' or 'roger'. Captain hook sailed a brig named Jolly Roger

**Comment by micahhausler** [comment]
For a backronym:

**R**ufio
**U**tilizes
**F**ancy
**I**PMI
**O**perations

**Comment by displague** [comment]
I'm asking the CNCF for recommendations on the `rufio` name.
#15 is one of the first steps there.

**Comment by micahhausler** [comment]
Closing this now that we have the repo

**Comment by displague** [comment]
Request for CNCF clarity submitted: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1261
