### ISSUE TITLE
[Organization/member]: request for chrisdoherty4

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/org#16]
### GitHub Username

chrisdoherty4

### Role

Maintainer

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [tinkerbell-contributors e-mail list](https://groups.google.com/g/tinkerbell-contributors)
- [X] I am actively contributing to 1 or more Tinkerbell subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@micahhausler

### Sponsor 2

@jacobweinstock

### List of contributions to the Tinkerbell project

https://github.com/tinkerbell/hegel/pull/84
https://github.com/tinkerbell/hegel/pull/86
https://github.com/tinkerbell/hegel/pull/87
https://github.com/tinkerbell/hegel/pull/82
https://github.com/tinkerbell/tink/pull/594
https://github.com/tinkerbell/tink/pull/593

Various issues.

And more to come :)

**Comment by micahhausler** [comment]
LGTM! Thanks Chris!

**Comment by chrisdoherty4** [comment]
I've been granted.
