### ISSUE TITLE
Consider not using google-groups

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/org#2]
Google groups currently requires google login just to view content and that doesn't seem very inclusive. Github doesn't require login to view our code, issues, PRs. This discrepancy is a sour point for me, and others that I've noticed out on the net.

2 alternative options I can think of at the moment would be:

1. mailing lists hosted on sr.ht: See sourcehut's own mailing lists as example: [https://sr.ht/~sircmpwn/sourcehut/lists](https://sr.ht/~sircmpwn/sourcehut/lists) 
2. Reddit: [rust](https://old.reddit.com/r/rust) is a well known example project using reddit for comms for a long time now. More recently [Go](https://old.reddit.com/r/golang/comments/hv976o/qa_iofs_draft_design/) has started experimenting with it too for proposal comms.

**Comment by mmlb** [comment]
@displague @thebsdbox

**Comment by mmlb** [comment]
Talking with @displague and it seems the public view is an option that needs to be toggled. Which I'm 100%. Still, would like to have this convo anyway.

**Comment by gianarb** [comment]
One of the reasons about why Google Group is cool is because subscribers receive a calendar invite as well.
I understand your concern and probably @thomcrowe is the right person to hook here.

**Comment by mmlb** [comment]
@gianarb calendar invite to what?

**Comment by gianarb** [comment]
weekly contributor meeting. A public event that contributors can join. If you are a member of the group you should have it in your calendar as well

**Comment by mmlb** [comment]
Ah gotcha. I think my main motivation has been addressed so if nothing else pops up then we can close and stay with GG.

**Comment by gianarb** [comment]
I will close this also because I want to archive this repo in favor of .github
