### ISSUE TITLE
[Organization/member]: request for abhinavmpandey08

### ISSUE THREAD

**Issue by abhinavmpandey08** [tinkerbell/org#24]
### GitHub Username

@abhinavmpandey08

### Role

Member

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [tinkerbell-contributors e-mail list](https://groups.google.com/g/tinkerbell-contributors)
- [X] I am actively contributing to 1 or more Tinkerbell subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jacobweinstock

### Sponsor 2

@displague 

### List of contributions to the Tinkerbell project

\# Issues or PRs created
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/130
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/176
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/176
- https://github.com/tinkerbell/tink/pull/610
- https://github.com/tinkerbell/tink/pull/613
- https://github.com/tinkerbell/tink/pull/617
- https://github.com/tinkerbell/tink/pull/624
- https://github.com/tinkerbell/boots/pull/272

\# Issues or PRs reviewed
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/160
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/184
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/182

**Comment by jacobweinstock** [comment]
+1 from me! glad to have you officially in @abhinavmpandey08 !

**Comment by displague** [comment]
+1 here - thanks for your contributions to date and yet to come, @abhinavmpandey08!

**Comment by jacobweinstock** [comment]
Invitation sent!

**Comment by micahhausler** [comment]
Solid, thanks for volunteering @abhinavmpandey08!
