### ISSUE TITLE
[Organization/member]: request for moadqassem

### ISSUE THREAD

**Issue by moadqassem** [tinkerbell/org#25]
### GitHub Username

@moadqassem

### Role

Member

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [tinkerbell-contributors e-mail list](https://groups.google.com/g/tinkerbell-contributors)
- [X] I am actively contributing to 1 or more Tinkerbell subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jacobweinstock

### Sponsor 2

@chrisdoherty4

### List of contributions to the Tinkerbell project

\# Issues or PRs created
- tinkerbell/sandbox#61
- tinkerbell/sandbox#63
- tinkerbell/sandbox#146
- tinkerbell/hub#40
- tinkerbell/hub#88
- tinkerbell/hub#91
- tinkerbell/tink#486
- tinkerbell/boots#298

**Comment by chrisdoherty4** [comment]
lgtm

**Comment by jacobweinstock** [comment]
100% approved!

**Comment by jacobweinstock** [comment]
will send out an invite shortly.
