### ISSUE TITLE
[Organization/member]: request for counihantom

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/org#27]
### GitHub Username

@counihantom

### Role

Member

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [tinkerbell-contributors e-mail list](https://groups.google.com/g/tinkerbell-contributors)
- [x] I am actively contributing to 1 or more Tinkerbell subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chrisdoherty4

### Sponsor 2

@jacobweinstock

### List of contributions to the Tinkerbell project

Tom consistently attends community meetings and provides valuable feedback with a keen interest in furthering Tinkerbell.

**Comment by chrisdoherty4** [comment]
+1

**Comment by counihantom** [comment]
Thanks Chris,
Am I to do anything specific re updating this 'issue'?

**Comment by chrisdoherty4** [comment]
@counihantom Affirm you've read the material etc in the `Requirements` section with a comment. I can check them off once affirmed.

**Comment by counihantom** [comment]
All checked "except [enabled 2FA on my GitHub account](https://github.com/settings/security)"
Will need a little time 'cos need to figure out which is the best vis-a-vis cost - all suggested require payment.

**Comment by counihantom** [comment]
Done:
"Two-factor authentication (2FA) is now enabled for your GitHub account"

**Comment by jacobweinstock** [comment]
+1

**Comment by jacobweinstock** [comment]
I will add that Thomas is active in the Tinkerbell slack channel and attends community meetings regularly. He's very keen to help others and has posted very helpful content like this: https://youtu.be/Y_FgPJn4siw
